/*
 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */
public class q2 {

	public static void main(String[] args) {
		
		int a=1,b=2,c=0,sum=0;
		System.out.println("Enter a number");
		
		for(int i=0;sum<4000000;i++)
		{
			if(a%2==0)
			{
				System.out.println(a);
				sum=sum+a;
			}
			c=a+b;
			a=b;
			b=c;
		}
		System.out.println("The sum of even numbers are "+sum);
	}

}
//answer = 4613732
